# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x0b\x63hat_system\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0bVectorClock\x12\r\n\x05\x63lock\x18\x01 \x03(\x05\"n\n\x0b\x43hatMessage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12.\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x18.chat_system.VectorClock\x12\x10\n\x08group_id\x18\x04 \x01(\t\"S\n\x13SubscriptionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x19\n\x11\x63lient_process_id\x18\x02 \x01(\x05\x12\x10\n\x08group_id\x18\x03 \x01(\t2\xa0\x01\n\x0b\x43hatService\x12?\n\x0bSendMessage\x12\x18.chat_system.ChatMessage\x1a\x16.google.protobuf.Empty\x12P\n\x10SubscribeToGroup\x12 .chat_system.SubscriptionRequest\x1a\x18.chat_system.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCK']._serialized_start=56
  _globals['_VECTORCLOCK']._serialized_end=84
  _globals['_CHATMESSAGE']._serialized_start=86
  _globals['_CHATMESSAGE']._serialized_end=196
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=198
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=281
  _globals['_CHATSERVICE']._serialized_start=284
  _globals['_CHATSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
